fossasia/pslab-desktop

.travis.yml

Just trying another way to solve build error.

copied PSL package to virtualenv

---

.travis.yml

Enable cache for packages installed via pip ( setuptools, , Pyqtgraph )

modified travis.yml to use pip cache . issue #104

---

PSL_Apps/bin/Experiments

rearranged import statements in bin/Experiments

---

virtual/virtualapp/static/css/signup.css
virtual/virtualapp/templates/signup.html
virtual/virtualapp/views.py

+ added a sign-up page & css, and appropriate hook in views.py
+ added sign-up functionality. frontend sends data via AJAX, and a mysql procedure is called by the backend to try and create a new user with the supplied credentials
Fixes #166 , #167

Virtual Lab sign up process

---

virtual/README.md
virtual/virtualapp/templates/signin.html
virtual/virtualapp/views.py

+ Created an html page for sign in
+ Created the corresponding hook in the backend
fixes #168

Virtual Lab SignIn page

---

.travis.yml

Fixed the build fail due to Travis update recently!
Thanks @jithinbp for the guide and info!
I've cloned the exisiting pslab-desktop-apps repo and edited travis.yml to test the build. Find it [here](https://travis-ci.org/CloudyPadmal/testPSLAB-Desktop-Apps/jobs/273757008)

Fixes #179 : Travis build failing

---

installer.sh

Added a shell script which can be made executable using 
`sudo chmod +x installer.sh`
and then run it by
`sudo ./installer.sh`
to install all the dependencies and finally the application and run it for the first time!

Fixes #176 : Shell script for installation

---

README.md

Updated README.md file with steps to use the `installer.sh`

Fixes #185: Updating README to include steps to install using installer

---

.travis.yml

Updated python version which was keep on failing Travis build

chore: tavis build fix

---

README.md

Also an additional grammar fix.

Remove code formatting for suggestions section

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Fixes #234
- Added issue template 
- Added PR template

Add issue and PR templates to the project

---

src/components/GraphPanelLayout/GraphPanelLayout.styles.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/Settings.styles.js
src/screen/Oscilloscope/components/settingOptions.js

Fixes: #238 
**Changes:**
**Screenshot**
**Note:** Slider for Timebase is not working

Add Settings for Oscilloscope instrument #238

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Adding Issue, PR template to master.
Currently added to v2, we want to use it ASAP @mariobehling
Fixes #236

Add Issue, PR template to master

---

src/background_tasks/linker.html
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/Graph.js
src/scripts/bridge.py
src/util/preProcessor.js

Fixes #256 
- Replaced map with naked for loop
- Created a separate utility file for keeping these functions
- Removed a redundant check from the communication loop
- Made communication more modular
- Made changes to the graph visuals
- Inserted initial data to graph state so that the graph doesn't come up empty when the component mounts.
No

Optimize the communication and preprocessing step, 2 channel integration

---

package.json
src/App.js
src/MUItheme.js
src/components/Appshell/Appshell.js
src/screen/Oscilloscope/components/ActionButtons.js
src/screen/Oscilloscope/components/ActionButtons.styles.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/Settings.styles.js
src/screen/PowerSource/components/Settings.js

Migrate From Antd to MUI #251 
Used Material UI Theme Provider for unifying colour scheme
Problem: 
- Slider of MUI is in experimental mode, won't show placeholder values. 
- Default value of select option
Yes

Migrate To MUI #251

---

.gitignore
package.json
public/electron.js
src/App.js
src/background_tasks/linker.html
src/components/Appshell/Appshell.js
src/components/Appshell/Appshell.styles.js
src/components/GraphPanelLayout/GraphPanelLayout.styles.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/ActionButtons.js
src/screen/Oscilloscope/components/ActionButtons.styles.js
src/screen/Oscilloscope/components/AnalysisParameters.js
src/screen/Oscilloscope/components/ChannelParameters.js
src/screen/Oscilloscope/components/PlotParameters.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/Settings.styles.js
src/screen/Oscilloscope/components/TimeParameters.js
src/screen/Oscilloscope/components/settingOptions.js
src/scripts/bridge.py
src/scripts/oscilloscope.py
src/theme.js

Fixes #268 
- Added a better pyscript communication model
- Converted Oscilloscope and Appshell for MUI integration
- Settings state added
- Themeing system added
No

Fixes #268: Oscilloscope MUI integration complete, py script improved

---

src/scripts/bridge.py

Fixes #272 
- Modified py script to set pcs, pc1, pc2, pc3 from the app
No

[#272] Added python code to change values of pcs, pc1, pc2, pc3

---

src/screen/Oscilloscope/components/ActionButtons.js
src/screen/Oscilloscope/components/AnalysisParameters.js
src/screen/Oscilloscope/components/PlotParameters.js
src/screen/Oscilloscope/components/TimeParameters.js

Fixes #277 
- Oscilloscope component refactored
- Console error fixed
No

[#277] Oscilloscope component refactored, key error fixed

---

public/electron.js
src/screen/PowerSource/PowerSource.js
src/scripts/bridge.py

Fixes #275 
- Connected the electron app with python script for the power source component
No

[#275] Electron app and pyscript connected for power source component

---

src/App.js
src/background_tasks/linker.html
src/components/Appshell/Appshell.js
src/screen/PowerSource/PowerSource.js
src/scripts/bridge.py
src/scripts/device_detection.py

Fixes #280 
- py script to check for device detection and disconnection
- snackbar to notify the user of device connection and disconnection
- icon indicator to show device connectivity status
- tooltip to show connected device information like portname device name
No

[#279] Automatic device connection and disconnection implemented

---

package.json
src/App.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/AnalysisParameters.js
src/screen/Oscilloscope/components/ChannelParameters.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/PlotParameters.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/TimeParameters.js

Fixes #281 
- Dynamic graph
- Settings linked to state
- electron-load-balancer version update
No

[#274] Oscilloscope settings linked to state

---

src/background_tasks/linker.html
src/screen/Oscilloscope/Oscilloscope.js
src/screen/PowerSource/PowerSource.js
src/scripts/bridge.py

Fixes #285 
- Power source component state now being fetched from the device
No

[#285] power source config data now being fetched from device

---

src/App.js

Fixes #283 
- used render prop instead of component prop
No

[#283] Oscilloscope remount bug fixed

---

src/components/GraphPanelLayout/GraphPanelLayout.styles.js
src/components/SimplePanelLayout/SimplePanelLayout.styles.js
src/screen/Oscilloscope/components/Graph.js
src/screen/PowerSource/components/Display.styles.js
src/screen/PowerSource/components/Settings.styles.js

- oscilloscope graph scale correctly with the screen size
- Power source cards now place centrally aligned
No

[#290] powersouce and oscilloscope graph ui fixed

---

public/electron.js
src/App.js
src/background_tasks/linker.html
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/TimeParameters.js
src/screen/PowerSource/PowerSource.js
src/scripts/bridge.py
src/scripts/oscilloscope.py
src/scripts/power_source.py

Fixes #288 #289
- Component config values now get synced to the device
- Trigger partially implemented, not completely tested
No

[#288] Device and app configuration sync, trigger partially working 

---

Makefile
PSL_Resources/GUI/A_TEST_AND_MEASUREMENT/A_TandM/templates/wirelessTemplate.ui
installer.sh

- Updated installer
- Fixed outdated UI file
- No
---

fix: webkit issue and updated installer

---

PSL_Apps/bin/Experiments
PSL_Resources/GUI/A_TEST_AND_MEASUREMENT/A_TandM/H_wireless_sensors.py
PSL_Resources/GUI/A_TEST_AND_MEASUREMENT/A_TandM/templates/wirelessTemplate.ui
README.md

fix: updated ui error

---

README.md

Fixes #299 
- Updated readme for the build pipeline
NO

[#299] README.md updated for build pipeline

---

scripts/bridge.py
scripts/device_detection.py
scripts/oscilloscope.py

Fixes #308 
- Move the read thread variables inside their respective classes
NO
Just run the component, they should work without breaking

[#308] Read threads moved inside respective insturment classes

---

scripts/bridge.py
scripts/oscilloscope.py
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/ChannelParameters.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/TimeParameters.js
utils/preProcessor.js

Fixes #317 
- Graph tick now changes based on timebase and channel range
- python script modified to accommodate the change in UI
- Preprocessor modified to for dynamic channel selection
No

[#317] Graph ticks now change based on use timebase and channel range

---

background_tasks/linker.html
scripts/bridge.py
scripts/oscilloscope.py
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/ChannelParameters.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/PlotParameters.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/TimeParameters.js
src/theme.js
utils/preProcessor.js

Fixes #319 
- All four channels can be read in parallel 
- Graph UI improved
- Added base for FFT
- Added biaxis
No

Graph UI improvement, 4 channel independence, FFT base code added, UI imporved

---

src/screen/Multimeter/components/Dial.styles.js

[#315] Fixed hiding of dial circle

---

background_tasks/linker.html
scripts/bridge.py
scripts/multimeter.py
src/App.js
src/screen/Multimeter/Multimeter.js

Fixes #329 
- Added a preprocessor to provide a formatted output for readings
- Depending on the range of output, a prefix will be added "M", "K", "m", "μ" in the output. 
- Data is now rounded off to the third decimal place
No

Multimeter python bridge script imporvement

---

src/screen/LogicAnalyser/LogicAnalyser.js
src/screen/LogicAnalyser/components/ActionButtons.js
src/screen/LogicAnalyser/components/ActionButtons.styles.js
src/screen/LogicAnalyser/components/ChannelParameters.js
src/screen/LogicAnalyser/components/Graph.js
src/screen/LogicAnalyser/components/Settings.js
src/screen/LogicAnalyser/components/Settings.styles.js
src/screen/LogicAnalyser/components/TimeParameters.js
src/screen/LogicAnalyser/components/settingOptions.js

I have added a UI for the logic analyser instrument.
No.

Logic analyser UI

---

scripts/multimeter.py
src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/Dial.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Multimeter/components/SettingOptions.js

Fixes #324 
- Restructured code
- Added minor optimization
- Device and Dial sync
No

[#324] UI Dial fix for multimeter

---

src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Multimeter/components/InstrumentCluster.styles.js
src/screen/Multimeter/components/SettingOptions.js

Fixes #323 
Switch added for pulse section inside multimeter component.
NO

[#323] switch added for pulse section

---

scripts/bridge.py
scripts/multimeter.py
scripts/oscilloscope.py
src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Multimeter/components/InstrumentCluster.styles.js
src/screen/Multimeter/components/MeasurementDisplay.js
src/screen/Multimeter/components/SettingOptions.js

Fixes #334 
- The bridge has now been linked with the UI
- Time out of 0.5 sec added for frequency function
No

Connect python multimeter bridge with UI

---

background_tasks/linker.html
scripts/oscilloscope.py
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/FFTGraph.js
src/screen/Oscilloscope/components/TimeParameters.js

- FFT feature works for all 4 channel simultaneously
No

[#333] FFT graph and python bridge implemented

---

src/App.js
src/components/CustomDialog/CustomDialog.js
src/components/CustomDialog/index.js
src/screen/LogicAnalyser/LogicAnalyser.js
src/screen/LogicAnalyser/components/ChannelParameters.js
src/screen/LogicAnalyser/components/Settings.js
src/screen/LogicAnalyser/components/TimeParameters.js
src/screen/LogicAnalyser/components/settingOptions.js
src/screen/PowerSource/PowerSource.js
src/screen/PowerSource/components/InstrumentCluster.js
src/screen/PowerSource/components/InstrumentCluster.styles.js

Fixes #340 
- Added a universal Dialog box that can be called from anywhere within the app
- Added a sample use case in the PV1 pannel of powersource
NO

[#340] Implemented universal Dialog box for the app

---

background_tasks/linker.html
public/electron.js
scripts/bridge.py
scripts/wave_generator.py
src/screen/WaveGenerator/WaveGenerator.js
src/screen/WaveGenerator/components/SquareWaveParameters.js
src/screen/WaveGenerator/components/settingOptions.js

Fixes #337 
- Complete the bridge between wave generator UI and python code
- Minor indentation fixes
No

Implement python bridge for wave generator

---

background_tasks/linker.html
package.json
public/electron.js
src/App.js

Fixes #314 
- Load balancer library updated
- Background task cleanup feature added
No

[#314] load-balancer version updated 1.0.9, background process cleanup added

---

background_tasks/linker.html
package.json
public/electron.js
scripts/bridge.py
scripts/multimeter.py
scripts/oscilloscope.py
scripts/power_source.py
scripts/wave_generator.py
src/App.js
src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/MeasurementDisplay.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/AnalysisParameters.js
src/screen/Oscilloscope/components/FFTGraph.js
src/screen/Oscilloscope/components/Graph.js
src/screen/PowerSource/PowerSource.js
src/screen/WaveGenerator/WaveGenerator.js

Fixes #345 
- load-balancer version update to 2.0.0
- redundant variables removed from js and python code
- added extra logic to improve the responsiveness of app while reading data
- Added separate listeners for different instruments
**YES**
- The app didn't break after my changes

Refactor python scipts and JS code

---

src/components/CustomDialog/CustomDialog.js
src/screen/PowerSource/components/InstrumentCluster.js

fixes #348 
Implemeted dialog for all the power source component
NO

[#348] Implemeted dialog for all the power source component

---

background_tasks/linker.html
public/electron.js
scripts/bridge.py
scripts/oscilloscope.py
src/components/GraphPanelLayout/GraphPanelLayout.js
src/components/GraphPanelLayout/GraphPanelLayout.styles.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/AnalysisParameters.js
src/screen/Oscilloscope/components/FitPanel.js
src/screen/Oscilloscope/components/FitPanel.styles.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/TimeParameters.js
src/utils/arithmetics.js

Fixers #357 
- Have implemented sine fitting option for the analysis section of the oscilloscope
No

[#357] Complete the Sine fitting functions for Oscilloscope

---

background_tasks/linker.html
public/electron.js
scripts/bridge.py
scripts/oscilloscope.py
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/FFTGraph.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/XYPlotGraph.js
utils/preProcessor.js

Fixes #363 
- Implemented the XY plot feature
- Added labels for all the graphs
- Added a safety time delay to prevent the board from overloading
No

[#363] XY plot complete

---

background_tasks/linker.html
scripts/oscilloscope.py
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/FitPanel.js
src/screen/Oscilloscope/components/FitPanel.styles.js

Fixes #360
- Implemented square fitting feature
- Made minor logic improvements
- Made minor UI improvements
No

[#360] Square fitting implementation complete

---

src/components/CustomSliderInput/CustomSliderInput.js

fixes #354
Updating InputSlider for using dialog box to update values
No

[#354] Updating InputSlider for using dialog box to update values

---

src/screen/Multimeter/Multimeter.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/PowerSource/PowerSource.js
src/screen/WaveGenerator/WaveGenerator.js

- I have done a minimalistic redux integration
NO

Minimalistic redux integration

---

scripts/bridge.py
scripts/wave_generator.py
src/screen/WaveGenerator/WaveGenerator.js
src/screen/WaveGenerator/components/Settings.js
src/screen/WaveGenerator/components/Settings.styles.js
src/screen/WaveGenerator/components/SineWaveParameters.js
src/screen/WaveGenerator/components/SquareWaveParameters.js
src/screen/WaveGenerator/components/settingOptions.js

Fixes: #351
- I have updated the UI of Wavegenerator 
- I have updated the python code accordingly
NO

[#351] PWM issue fixed

---

background_tasks/linker.html
package.json
public/electron.js
src/App.js
src/redux/store.js

Fixes #245
- Added dev tool support for react and redux
- Minor bug fix for fft
NO

[#245] React and Redux devtool support added

---

src/App.js
src/components/Appshell/Appshell.js

Fixes #366 
- Added an extra feature to manually reset the device if the device freezes
No

[#366] Device reset option added

---

src/screen/WaveGenerator/WaveGenerator.js
src/screen/WaveGenerator/components/Graph.js
src/screen/WaveGenerator/components/Settings.js
src/screen/WaveGenerator/components/SineWaveParameters.js
src/screen/WaveGenerator/components/SquareWaveParameters.js

[#379] PWM switch fix

---

src/components/GraphPanelLayout/GraphPanelLayout.js
src/components/GraphPanelLayout/GraphPanelLayout.styles.js
src/screen/LogicAnalyser/components/ActionButtons.styles.js
src/screen/LogicAnalyser/components/Graph.js
src/screen/LogicAnalyser/components/Settings.styles.js
src/screen/Oscilloscope/components/ActionButtons.styles.js
src/screen/Oscilloscope/components/FFTGraph.js
src/screen/Oscilloscope/components/FitPanel.styles.js
src/screen/Oscilloscope/components/Graph.js
src/screen/Oscilloscope/components/Settings.js
src/screen/Oscilloscope/components/Settings.styles.js
src/screen/Oscilloscope/components/XYPlotGraph.js

Fixes #385 
- x ] Feature implementation
Changed layout for oscilloscope and logic analyser
NO

[#385] Layout for oscilloscope changed

---

scripts/bridge.py
src/components/SimplePanelLayout/SimplePanelLayout.styles.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Multimeter/components/InstrumentCluster.styles.js
src/screen/PowerSource/components/InstrumentCluster.styles.js
src/screen/WaveGenerator/WaveGenerator.js

Fixes: #386
- Modified multimeter UI
- Removed redundant code
NO

[#386] Multimeter Layout changed

---

src/components/CustomKnob/CustomKnob.js
src/components/CustomKnob/index.js
src/components/CustomKnob/skins/s3.js
src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/Dial.js
src/screen/Multimeter/components/InstrumentCluster.js

Fixes #394
- Added a custom lifelike dial for the multimeter component
- NO

[#394] Custom Dial added to multimeter

---

package.json

- [ tick] The commit message follows our guidelines
- [ tick] Bug fix
added missing dependency
no
Just see package.json

add react-rotary-knob as dependency #fixes 396

---

src/screen/LogicAnalyser/components/AnalysisParameters.js
src/screen/LogicAnalyser/components/ChannelParameters.js
src/screen/LogicAnalyser/components/NumberParameter.js
src/screen/LogicAnalyser/components/Settings.js
src/screen/LogicAnalyser/components/Settings.styles.js

Fixes #377
- Completed logic analyser UI
- Made changes to make the UI far more similar to mobile app
- Added a table to take time measurements and record them as in the python-desktop app
No

[#377] Completed Logic Analyser UI

---

src/App.js
src/components/CustomDialog/CustomDialog.js
src/components/CustomSliderInput/CustomSliderInput.js
src/redux/actions/app.js
src/redux/reducers/app.js
src/screen/PowerSource/components/InstrumentCluster.js

Add property inputCheck to allow developer to specify what kind of input he wants. He can pass function to inputCheck. Function should return true or false.
no

[#393] Fix Power source component freezes

---

src/screen/Home/components/InstrumentCard.js
src/screen/Home/components/InstrumentCard.styles.js
src/screen/Home/components/Tabs.js
src/screen/Home/components/Tabs.styles.js

- Added lines in cards.
- Changed layout of cards
NO

[#413] Make card layout look exactly same, improve layout

---

background_tasks/linker.html
public/electron.js
scripts/bridge.py
scripts/file_write.py
scripts/oscilloscope.py
src/App.js
src/redux/reducers/config.js
src/redux/store.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/Oscilloscope/components/ActionButtons.js

Fixes #410
- File writing feature from oscilloscope reading
No

File writing from oscilloscope reading

---

scripts/bridge.py
scripts/robotic_arm.py

Fixes #428
- Added python code to interact with servo motors
NO

[#428] Robotic arm python script finished

---

src/App.js
src/components/Icons/PSLabIcons.js
src/screen/Home/components/Tabs.js
src/screen/Sensors/Sensors.js
src/screen/Sensors/index.js
src/screen/Sensors/styles.js

fixes #430 
- Added a new screen **same as android** to connect external sensors
NO

sensor detection screen completed

---

scripts/robotic_arm.py
src/App.js
src/components/CustomCircularInput/CustomCircularInput.js
src/components/CustomSliderInput/CustomSliderInput.js
src/screen/Home/components/Tabs.js
src/screen/RobotArm/Components/KnobControl.js
src/screen/RobotArm/Components/PaintArea.js
src/screen/RobotArm/Components/styles.js
src/screen/RobotArm/RobotArm.js
src/screen/RobotArm/RobotArm.styles.js
src/screen/RobotArm/index.js

Fixes #426 
- Basic robot arm interface created
- Custom dialogue added to change the value of each servo
- Drag and paint option for servo values
No

[#426] Complete Robot Arm UI

---

scripts/bridge.py
scripts/file_write.py
scripts/wave_generator.py
src/App.js
src/components/Appshell/Appshell.js

Fixes #433 
- Save button added to navbar
- config of wave generator can be saved to file
- The saved file appears in data logger
No

[#433] Wave generator configuration save feature

---

src/screen/RobotArm/Components/KnobControl.js
src/screen/RobotArm/RobotArm.js

Fixes #435 
- Play/Pause Stop buttons are disabled if the device is not connected
No

[#435] Robot arm device connectivity fixed

---

scripts/file_write.py
scripts/wave_generator.py

Fixes #440 
- Added the missing variable in the CSV
No
I have checked the CSV file for missing value

[#440] Missing variable in Wave Generator CSV fixed

---

scripts/bridge.py
scripts/file_write.py
scripts/power_source.py
src/components/Appshell/Appshell.js

Fixes #439 
- I have added a CSV config logger for the power source component
No
The user is presented with a save button using which the power source config file will be saved to the default save folder

[#439] Save feature added for power source component

---

scripts/file_write.py
src/components/Appshell/Appshell.js
src/screen/LoggedData/LoggedData.js
src/screen/LoggedData/LoggedData.styles.js

Fixes #443 
- user can now import CSV files into the data logger screen
- user can now export CSV files to destination folder from the data logger screen
No
The interface appbar comes with a import button
Each tab comes with an export button

[#443] Import / Export CSV file feature added to data logger

---

PSL_Resources/GUI/A_TEST_AND_MEASUREMENT/A_TandM/B_Logic_Analyzer.py

Syntax error fixed
Run Logic Analyzer in python desktop app

[Fix #449]Logic analyzer output bug

---

scripts/bridge.py
scripts/file_write.py
scripts/multimeter.py
src/App.js
src/screen/Multimeter/Multimeter.js
src/screen/Multimeter/components/ActionButtons.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Oscilloscope/components/ActionButtons.js

- Data logging boilerplate implemented for multimeter
- Minor modifications in multimeter and oscilloscope UI
No

[#445] Data logger implemented for multimeter

---

scripts/file_write.py

Fixes #451 
- The file naming of data logger has been changed to match that of android
No

[#451] File naming corrected to match android

---

background_tasks/linker.html
scripts/bridge.py
scripts/logic_analyser.py
src/screen/LogicAnalyser/LogicAnalyser.js

Fixes #424 
- Completed python implementation for LA
- NO

[#424] Finish Logic analyser python implementation

---

src/components/Appshell/Appshell.js
src/screen/LoggedData/LoggedData.js

Fixes #453 
- Icon changed for import and export 
No

[#453] Import / Export icons changed

---

src/screen/WaveGenerator/WaveGenerator.js
src/screen/WaveGenerator/components/AnalogController.js
src/screen/WaveGenerator/components/DigitalController.js

Fixes  #458
- New wave generator UI linked to old JS functions
No
- Tested with device ( working as expected )

[#458] Link wave generator functions to the new UI

---

background_tasks/linker.html
scripts/file_write.py

Fixes #461 
- Naming conventions fixed for config files
NO
- Tested

[#461] Naming convention fixed for config files

---

scripts/bridge.py
scripts/file_write.py
scripts/power_source.py
src/App.js
src/screen/LoggedData/LoggedData.js
src/screen/PowerSource/PowerSource.js

Fixes #459
- The playback option for the power source component is partially done
No
- Tested with Power source and it is working as expected.

[#459] Read and set config values from csv file for Power Source

---

scripts/bridge.py
scripts/file_write.py
scripts/wave_generator.py
src/App.js
src/screen/LoggedData/LoggedData.js
src/screen/WaveGenerator/WaveGenerator.js

Fixes #463 
- Now config files for wave generator can be read and restored from csv files
- NO
- Working as expected

[#463] Restore config implemented for wave generator

---

background_tasks/linker.html
public/electron.js
scripts/bridge.py
scripts/logic_analyser.py
src/screen/LogicAnalyser/LogicAnalyser.js
src/screen/LogicAnalyser/components/Graph.js
src/screen/WaveGenerator/WaveGenerator.js
utils/preProcessor.js

Fixes #465
- Python LA bridged with UI
- NO

[#465] Python LA bridge with UI completed

---

.travis.yml
travis-scripts/upload-packages.sh

chore: push packages to install branch with travis

---

src/screen/LogicAnalyser/components/Graph.js
src/screen/LogicAnalyser/components/Settings.js

Fixes #474
- Improved ticks on the x axis
- Hide redundant analysis feature from screen
No

[#474] LA graph improved

---

scripts/logic_analyser.py
src/screen/LogicAnalyser/LogicAnalyser.js
src/screen/LogicAnalyser/components/Graph.js
utils/preProcessor.js

Fixes  #476
- Improved UI feedback
- LA main function cleaned up
No
Tested with device, working as expected

[#476] logic analyser python logic improvement

---

README.md
package.json

- build script and docs updated
No

Windows exe build

---

public/electron.js
src/App.js
src/components/Appshell/Appshell.js
src/components/Appshell/Appshell.styles.js
src/screen/Multimeter/Multimeter.js
src/screen/Oscilloscope/Oscilloscope.js

- Remove play button
- Auto data fetch for oscilloscope
- Record button shifted to app bar
- NO

[#492] Read button removed, record button shifted

---

package.json
scripts/file_write.py

Fixes #497 
I have added Two empty columns namely longitude and latitude with empty values in them.
No.
Will have to generate a csv file after connecting to a device to preview the new csv file.

Add blank latitude and longitide columns in generated csv file

---

src/screen/Home/components/InstrumentCard.styles.js
src/screen/Home/components/Tabs.js
src/screen/Home/components/Tabs.styles.js

Fixes #501 
I have made the cards align to the center in case of even cards in a row but aligned to start if the number is odd. 
No.

Home Screen Cards Alignment

---

src/screen/Layout/BackLayout.js

[ #480] Backlayout pin guide complete

---

background_tasks/playback.html
public/electron.js
scripts/file_write.py
scripts/playback_bridge.py
scripts/playback_robot.py
src/App.js
src/components/Appshell/Appshell.js
src/screen/LoggedData/LoggedData.js
src/screen/Oscilloscope/Oscilloscope.js
src/screen/RobotArm/RobotArm.js

- Robot arm config save option
No

 [#509] Robotic arm config saving feature 

---

src/components/Appshell/Appshell.js
src/components/Appshell/Appshell.styles.js

#513
- Instrument title added
No

Instrument name added

---

src/components/Appshell/Appshell.js
src/screen/LoggedData/LoggedData.js
src/screen/LoggedData/LoggedData.styles.js

#525  #526
- Settings icon removed
- data logger loading animation removed
No

circular loading removed from data logger

---

src/screen/WaveGenerator/components/Settings.styles.js

#518
- Sizes of analogue and digital board stay the same now
No

Wavegen width issue fixed

---

src/screen/RobotArm/Components/KnobControl.js
src/screen/RobotArm/Components/styles.js
src/screen/RobotArm/RobotArm.js
src/screen/RobotArm/RobotArm.styles.js

#540
- Robot arm UI placed in the center
- Icon size increased
- Tooltip added
No

Robot arm UI fixed

---

src/screen/LoggedData/LoggedData.js

#531
- PSLab folder gets auto-created while using data logger
No

folder auto creation added

---

src/screen/WaveGenerator/WaveGenerator.js
src/screen/WaveGenerator/components/AnalogController.js
src/screen/WaveGenerator/components/DigitalController.js
src/screen/WaveGenerator/components/Settings.styles.js

Fixes: #516 #515
- Wavegenerator UI improved according to android
No

Wave generator UI improved

---

src/screen/Multimeter/components/Dial.js
src/screen/Multimeter/components/Dial.styles.js
src/screen/Multimeter/components/InstrumentCluster.js
src/screen/Multimeter/components/InstrumentCluster.styles.js
src/screen/Multimeter/components/SettingOptions.js

#514
- Multimeter dial more responsive
- Angles now match android 
- Add background lines for multimeter and adjust the height of the component.
No
I could not find the digital font on Google fonts, so, for  now, I have not made that change. Will raise another issue for this later on.

Multimeter UI fix 

---

src/components/Appshell/Appshell.js

I have removed the back icon from the home screen and add text "Pocket Science Lab-PSLab" on the top bar. Fixes #549 
No. 

remove back icon from home screen and add text "Pocket Science Lab"

---

.travis.yml

chore: fix travis deployment error

---

README.md

Add info in README.md about npm mirrors in China, add a shell command line and a url in description.
This pull request is related to #558 
No

Add info in README.md about npm mirrors in China

---

src/screen/Home/components/InstrumentCard.styles.js

Fixes #535 
I have removed the pixelation issue that was initially occurring. 
No.

Remove Pixelation

---

package.json
public/electron.js
src/screen/AboutUs/AboutUs.styles.js

- fixes #567 
- Upgraded Concurrently package
- Fixed the UI responsiveness of about page
No
**Before**
**After**

upgraded concurrently package and fixed about page

---

public/electron.js

Added a new attribute within the BrowserWindow initialization to limit the width and height to a minimum.
No
As can be viewed, the minimizing capability is limited after a certain limit.

Add minimum size restraints

---

.travis.yml

chore: update time limit for build

---

src/screen/WaveGenerator/components/AnalogController.js
src/screen/WaveGenerator/components/DigitalController.js

Changed from just data-type comparison to strict comparison at some left places where it was not implemented.
No
Go to `DigitalController.js` and `AnalogController.js` files for the issue.

Changing to strict comparison between variables

---

src/screen/WaveGenerator/components/AnalogController.js

Removed the use of duplicate props in `AnalogController.js` file.
No

Removing the use of duplicate props

---

README.md

Issue fixed: #230
Add Documentation for installing PSLad in Mac OS
No
https://github.com/kumuditha-udayanga/pslab-desktop/blob/development/README.md

Add documentation for installing on Mac os

---

src/components/Appshell/Appshell.js
src/components/Icons/PSLabIcons.js
src/screen/AboutUs/AboutUs.js
src/screen/DeviceScreen/DeviceScreen.js
src/screen/Layout/BackLayout.js
src/screen/Layout/FrontLayout.js
src/screen/WaveGenerator/components/AnalogController.js
src/screen/WaveGenerator/components/DigitalController.js

Added alt prop to img tags so as to remove the jsx console errors.
No

Added alt prop

---

src/components/GraphPanelLayout/GraphPanelLayout.js
src/components/SimplePanelLayout/SimplePanelLayout.js
src/redux/reducers/config.js
src/screen/LogicAnalyzer/components/Settings.js
src/screen/RobotArm/RobotArm.js

Commented out some imports for now which are not in use.
No
Fixes #599

Commented out useless imports

---

src/screen/FAQ/FAQ.js

Fixed the error as mentioned in the issue #601 
No

Fixed the jsx error for console

---

src/screen/PowerSource/components/InstrumentCluster.js

Removed unnecessary escape character in `InstrumentCluster.js` file.
No

Removing unnecessary escape character

---

src/screen/Multimeter/components/Dial.js

As an arrow function is expected to return a value, so returned null in arrow function in `Dial.js` file.
No

Fixed arrow function return value

---

scripts/bridge.py
scripts/logic_analyser.py
src/screen/LogicAnalyzer/LogicAnalyzer.js
src/screen/LogicAnalyzer/components/Settings.js
src/screen/LogicAnalyzer/components/TimeParameters.js

Fixes #502 
I have added the timebase slider in logic analyzer. Earlier it was missing.
no
@AakashMallik

add captureTime slider in logic analyser

---

package.json

fixed the start script for development, see also https://github.com/fossasia/pslab-desktop/commit/d95758cddb4abb060ade7feb9eab68f373a8b1db#r40330639
no
`npm start`

revert start script to d95758cddb4abb060ade7feb9eab68f373a8b1db~1

---

scripts/multimeter.py
scripts/oscilloscope.py

Change front end to use new oscilloscope back end. This PR goes together with https://github.com/fossasia/pslab-python/pull/129. Neither should be merged before both are ready.
This PR is ready for merge.
https://github.com/fossasia/pslab-python/pull/129 is a breaking change, which this PR fixes. 
When this and https://github.com/fossasia/pslab-python/pull/129 are both used together, the front end should behave exactly like before.

Use new oscilloscope backend

---

scripts/logic_analyser.py

Necessary changes for pslab-desktop to work with the refactored logic_analyzer module from PSL.
The packet_handler refactorization of PSL broke the logic analyzer part of pslab-desktop (my bad!). To see the logic analyzer in a working state prior to this PR, use 20c62b2 from pslab-desktop and a74d48f from pslab-python.
The plotting functionality was and is rather buggy. Not sure if this PR makes it worse, as it didn't work very well before either.

Use new logic analyzer back end

---

README.md
docs/screenshots-and-demos.md

document IPC, stack, development setup, build instructions and distribution
no

Documentation overhaul: development, build and distribution

---

scripts/wave_generator.py

https://github.com/fossasia/pslab-python/pull/148

Backend waveform API update

---

scripts/oscilloscope.py

https://github.com/fossasia/pslab-python/pull/149

Backend oscilloscope API update

---

scripts/multimeter.py
src/screen/Multimeter/components/SettingOptions.js

https://github.com/fossasia/pslab-python/pull/150

Backend multimeter API update

---

scripts/bridge.py
scripts/robotic_arm.py

https://github.com/fossasia/pslab-python/pull/151

Backend servo API update

---

scripts/power_source.py

See https://github.com/fossasia/pslab-python/pull/158.

Backend power supply API update

---

scripts/wave_generator.py

PSL 2.0.0 [renamed this function](https://github.com/fossasia/pslab-python/commit/839c9496719ee9abc39d7f4072a36e79dc7f5c73)
No
Desktop application tested, and works properly now

Fix: Updated wavegen.load_equation calls to wavegen.load_function

---

.gitignore
README.md

Development is recommended to be done within a virtual environment to isolate the
development environment.
Resolves #638.
Added steps to the README that explain how to set up a virtual environment for development. 
No.
venv setup works on Kubuntu 20.04 with bash, and Windows 10 with cmd.

Docs: added venv setup to README.md

---

README.md

README: Document Chocolatey package for Windows
