fossasia/pslab-desktop

- psl_res/GUI/A_TEST_AND_MEASUREMENT/A_TandM/F_sensors.py
-Functions without arguments are created as QMenuAction
Screenshot from MPU6050 being used with the data_logger
> Improved GUI menus for Sensor Data Logger

- .travis.yml
The build has failed with previous approaches that used the Makefile, and setup.py
This approach adds the pslab-python repository to the global path
issue #114
> add pslab-python to the $PATH global variable in travis.yml

- docs/_includes/html5_video.html
embed videos using the HTML5 video player . Also has support for adding a title, and a poster.
Example text for embedding sample_video.ogg in a doc file
`{% include html5_video.html poster="images/poster.jpg" url="screencasts/sample_video.ogg" title = "this is the title : Click to play video" %}` 
Videos have fixed width at 600px , and options need to be explored for fluid width for html5 video
fixes #150
> added Jekyll include file for HTML5 video player

- installer.sh
Fixes #198 
When the installation is complete, confirmation to open PSLab desktop app will be asked using a dialog box.
> docs: added dialog box to open Desktop app

- PSL_Apps/saveProfile.py
- PSL_Apps/utilitiesClass.py
- PSL_Apps/utilityApps/advancedCal.py
- PSL_Apps/utilityApps/deviceInfo.py
- PSL_Apps/utilityApps/plotSaveWindow.py
- PSL_Apps/utilityApps/spreadsheet.py
- psl_res/GUI/A_TEST_AND_MEASUREMENT/A_TandM/Z_designer.py
- psl_res/GUI/B_ELECTRONICS/B_Diodes/L_DiodeClamping.py
- psl_res/GUI/B_ELECTRONICS/B_Diodes/L_DiodeClipping.py
- psl_res/GUI/B_ELECTRONICS/B_Diodes/L_halfWave.py
- psl_res/GUI/B_ELECTRONICS/B_Diodes/M_FullWave.py
- psl_res/GUI/B_ELECTRONICS/B_Opamps/L_Inverting.py
- psl_res/GUI/B_ELECTRONICS/B_Opamps/L_LinearRampGen.py
- psl_res/GUI/B_ELECTRONICS/B_Opamps/L_NonInverting.py
- psl_res/GUI/B_ELECTRONICS/B_Opamps/Precision_Rectifier.py
- psl_res/GUI/B_ELECTRONICS/B_Oscillators/L_WIEN_BRIDGE.py
- psl_res/GUI/B_ELECTRONICS/B_Oscillators/M_Monostable.py
- psl_res/GUI/C_ELECTRICAL/D_electrical/Q_RC_integ_deriv.py
- psl_res/GUI/D_PHYSICS/B_physics/B_SpeedOfSound.py
- psl_res/GUI/E_MISCELLANEOUS/B/calibration_loader.py
- psl_res/GUI/E_MISCELLANEOUS/B/virtual.py
These changes should be compatible with both Python 2 and Python 3.
* Old style exceptions --> new style
* Define __unicode()__ in Python 3
* Define __xrange()__ in Python 3
* Removed a few unused imports (Codacy seems to like that)
* Ran __isort__ on a few confusing import blocks
Some issues remain...
[flake8](http://flake8.pycqa.org) testing of https://github.com/fossasia/pslab-desktop-apps on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
flake8 . $F8OPTS
./PSL_Apps/utilitiesClass.py:1386:12: F821 undefined name 'a'
if link: a['LINK'] = link
^
./psl_res/GUI/E_MISCELLANEOUS/B/calibrator.py:345:12: F821 undefined name 'r'
if c and r:
^
./psl_res/GUI/E_MISCELLANEOUS/B/ADS1115calibrator.py:297:12: F821 undefined name 'r'
if c and r:
^ …
```
> Modernize Python 2 code to get ready for Python 3

- src/components/Appshell/Appshell.js
- src/screen/LoggedData/LoggedData.js
- src/screen/LoggedData/LoggedData.styles.js
- src/utils/fileNameProcessor.js
Fixes #446 
- File names now displayed in tabs in file viewer
- File names truncated if too long
- File name extractor moved to the utility file
> [#446] Truncated file names now displayed in file viewer

- src/components/HomeLayout/HomeLayout.styles.js
- src/screen/Home/components/InstrumentCard.styles.js
- src/screen/Home/components/Tabs.js
- src/screen/Home/components/Tabs.styles.js
I have shown Instrument Tiles in responsive way depending on the screen size
Fixes  #533
No
> create reponsive multicard layout home screen

- scripts/device_detection.py
fixed a typo in the Python bridge, found when trying out https://github.com/fossasia/pslab-python/pull/121
no
check the current code in the Python lib - it's the correct spelling: `verbose`
> Fix typo `vebose` => `verbose` in Python bridge

- .travis.yml
- package-lock.json
- package.json
This is a redo of the CI setup to publish artifacts on tags, adding v2.2.0. :crossed_fingers:
> redo ci setup

- background_tasks/linker.html
- background_tasks/playback.html
- package.json
- utils/bundling.js
This reenables asar bundling, reducing the size of the installed app to 447M (which is still much though, 263M for the asar bundle alone). Also fix the lookup path for the Pyththon scripts in release builds.
> Reenable asar

- background_tasks/linker.html
- background_tasks/playback.html
I removed the `pythonPath: 'python3'` option given to the python shell. This is unnecessary as python3 is already the default for non-Windows systems. For Windows systems `py` is the default pythonPath.
This update fixes the bug where PSLab Desktop on Windows would not connect to the board unless python3 was linked to python with `mklink python3.exe python.exe` in the Python installation folder.
No
PSLab Desktop was rebuilt with the new code and tested on Kubuntu 20.04 and Windows 10. The board was able to connect and …
> Remove pythonPath option given to python-shell module.

- scripts/bridge.py
- scripts/oscilloscope.py
This fixes the bug where the oscilloscope would not return to normal
operational mode after the X/Y plot was disabled.
Fixes #658 and fixes potentially problematic line.
No.
Tested on Kubuntu 20.04
> Fix #658 - Oscillosope not disabling X/Y Plot properly

- src/screen/LoggedData/LoggedData.js
Fixes bug where opening the datalogger would crash PSLab. Problem occurs
when the user doesn't have a Documents folder in the home location. The
PSLab directory fails to be made and the application crashes when
accessing this nonexistent directory.
Closes #661 
The folder where PSLab data is stored (currently hard coded as `OS_HOME_DIR/Documents/PSLab`  is now created recursively so the directory is still valid if the user doesn't have a `Documents` folder at the home location.
No.
Application crash no longer occurs on …
> Fix: viewing datalogger crashes application

- scripts/logic_analyser.py
This prevents a long period of nothing interesting happening from being plotted, which used to take up valuable screen real estate. Partly fixes #665.
> Logic analyzer: Don't plot first data point

- src/components/CustomDialog/CustomDialog.stories.js
- src/components/CustomSliderInput/CustomSliderInput.js
- CustomDialog story would crash if the dialog option was closed, because the onDialogClose function wasn't declared. Now it is.
- Convert value type to Number in CustomSliderInput - this was happening implicitly and giving warnings.
> Fix bugs in CustomDialog story and CustomSliderInput

- scripts/file_write.py
Uses os.path.join to build file path for file logging and replaces
colons with Windows safe unicode version.
- Uses `os.path.join` to build file path for file logging 
- Replaces colons with Windows safe unicode version
fixes #678 
No.
Data Recording works on Windows 10 now and still works on Kubuntu 20.04
> fix (FileWrite): Windows recording file bug

- src/screen/Oscilloscope/components/ChannelParameters.js
- src/screen/WaveGenerator/components/SineWaveParameters.js
* **Problem**
The Oscilloscope ChannelParameters and the Waveform SineWaveParameters have
both a global style, and a local style they need to be exported with. The use
of the withStyles function was previously incorrect, and as a result, neither
style was getting applied.
I reworked the way `withStyles` was called to function correctly. Before we were trying to create an object containing the spread of two functions. Trying to spread a function will result in an error and the resulting object will be `null`. The changes fix this issue while maintaining the desired behavior of both styles applying.
fixes #682 …
> fix: Export components with formStyles correctly

- src/screen/WaveGenerator/components/DigitalController.js
Increased square frequency limit to 10MHz
Fixes #640 
No
Command is sent to PSLab Python without errors. The period is too fast to be detected by the PSLab Oscilloscope.
> fix (waveform): Increase square frequency limit to 10MHz

- public/electron.js
- src/App.js
- src/components/Appshell/Appshell.js
- src/screen/LoggedData/LoggedData.js
- src/utils/fileNameProcessor.js
Remote calls are removed in preparation for Electron 10, and
showOpenDialog calls in Datalogger are fixed. showOpenDialog was
promisified in Electron 7 and file import/export has been broken
ever since.
feat (File Import) - Allows multiple files to be selected
refactor (File Import): Removed remote usage
Main process now handles the dialog window creation and file copying.
refactor (Logged Data): Removed remote usage
Main process now handles the dataPath directory creation, directory
reading, Export File dialog, and deleting files.
dataPath is now pulled from App props instead of redefining it in
LoggedData.
refactor: Set enableRemoteModule to false
fix: Export and Import snackbox messages
* **What kind of change does this PR …
> refactor: Migrate from remote and fix Datalogger

- src/screen/LogicAnalyzer/LogicAnalyzer.js
- src/screen/LogicAnalyzer/components/ActionButtons.js
- src/screen/LogicAnalyzer/components/ActionButtons.styles.js
- src/screen/LogicAnalyzer/components/Graph.js
- src/screen/LogicAnalyzer/components/Settings.js
- src/screen/LogicAnalyzer/components/TimeParameters.js
Capture time slider is changed to allow for larger values and more
fine-tuned control. Auto Recapture checkbox added to have the logic
analyzer continuously recapture until an event is detected.
The Graph component is receiving the LA data and if a capture has no
event within it and the auto recapture is on, the LA is toggled
back on.
Standarized UI to use μs which is converted to ms for the backend communication.
Fix (Logic Analyzer): Define inputCheck
The CustomDialog dispatch needs an inputCheck function to be defined.
The Logic Analyzer capture time slider will always be an
non-negative float so inputCheck will check for that.
No tests or docs were added. Do we have a unit test framework for UI elements that need parts of the …
> Feat (Logic Analyzer): Auto Recapture and Capture Time slider
